// File generated by FlutterFire CLI.
// This file is used to configure Firebase for your Flutter app.
// Note: This is a dummy configuration file for demonstration purposes.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Dummy Firebase configuration for Web
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:1234567890:web:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'dbit-placement-portal',
    authDomain: 'dbit-placement-portal.firebaseapp.com',
    storageBucket: 'dbit-placement-portal.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );

  // Dummy Firebase configuration for Android
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:1234567890:android:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'dbit-placement-portal',
    storageBucket: 'dbit-placement-portal.appspot.com',
  );

  // Dummy Firebase configuration for iOS
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:1234567890:ios:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'dbit-placement-portal',
    storageBucket: 'dbit-placement-portal.appspot.com',
    iosClientId: 'dummy-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.dbit.placementportal',
  );

  // Dummy Firebase configuration for macOS
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'dummy-api-key',
    appId: '1:1234567890:ios:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'dbit-placement-portal',
    storageBucket: 'dbit-placement-portal.appspot.com',
    iosClientId: 'dummy-ios-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.dbit.placementportal',
  );
}
